package DomainLayer.Market.Users.Roles;

public enum StorePermissions {
    STORE_COMMUNICATION,
    STORE_SALE_HISTORY,
    STORE_STOCK_MANAGEMENT,
    STORE_ITEM_MANAGEMENT,
    STORE_POLICY_MANAGEMENT,
    STORE_DISCOUNT_MANAGEMENT,
    STORE_MANAGEMENT_INFORMATION,
    STORE_OWNER,
    STORE_FOUNDER
}
